name: Build

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'build/**'
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package shade:shade -DskipTests