name: Build

on:
  push:
    branches:
      - '**'  # 모든 브랜치에 대해 트리거
    paths:
      - '.github/workflows/**'
      - 'build/**'
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package shade:shade -DskipTests

      # Main 브랜치에 push된 경우에만 Docker Hub에 push 작업 진행
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            dlsrks1021/movinfo-messenger:latest
