name: Deploys

on:
  pull_request:
    types: [closed]
    branches:
      - main 
    paths:
      - 'version/version.txt'

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Maven environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package shade:shade -DskipTests

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat ./version/version.txt)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: |
            dlsrks1021/movinfo-messenger:latest
            dlsrks1021/movinfo-messenger:${{ env.VERSION }}